### ISSUE TITLE
Recognise mentions and hashtags separated with just "/" without spaces

### ISSUE THREAD

**Issue by Symbian9** [zedeus/nitter#373]
- https://twitter.com/app4soft/status/1383720715174612997
  - https://nitter.fdn.fr/app4soft/status/1383720715174612997

![Twitter vs Nitter](https://i.imgur.com/wIsgfOW.png)

**Comment by zedeus** [comment]
Fixed by #279

**Comment by Symbian9** [comment]
@zedeus, Issue still appears if there are such sequence as `#hashtag1/#hashtag2/#hashtag3/...`

See `@SolveSpace` account description:

- https://nitter.unixfox.eu/solvespace

![Screenshot_2022-01-04_10-11-51](https://user-images.githubusercontent.com/13188580/148029191-cf187b08-e7ff-4ae1-a83b-e1c845c1efb0.png)
