### ISSUE TITLE
Feature request: Add a feature to hide “twitter blue” repliers by default.

### ISSUE THREAD

**Issue by StyMaar** [zedeus/nitter#824]
Feature request: add a feature (at the instance level or maybe at the user preference level) to hide all replies from paid “twitter blue” subscribers

Rational: 
- the legacy legit “confirmed” twitter users recently lost there blue check, letting only paid subscribers with the said check.
- recent policy change at twitter put “twitter blue” users response always on top, giving a lot of nuisance power to people willing to spend $8 a month in subscription.

Subjective motivation: I'm personally quite annoyed to see only response tweet from overenthusiastic Musk fans below every single tweet I read.

**Comment by axel37** [comment]
Alternatively, it could de-prioritize those answers, if possible ?

**Comment by zedeus** [comment]
It would be possible to hide them, but that seems a bit silly. You could create a userscript to do the same fairly easily. De-prioritizing would be impossible.

**Comment by JodanJodan** [comment]
> You could create a userscript to do the same fairly easily.

Yes, but unlike Twitter which quickly populates more replies through JS until the view is filled, this just results in an empty comment section on Nitter due to its static nature, and the user has to keep sequentially following `Load more` to get to the first non-subscriber replies.

**Comment by zedeus** [comment]
To avoid reloading, enable infinite load on the preferences page.

**Comment by JodanJodan** [comment]
> To avoid reloading, enable infinite scroll on the preferences page.

Infinite scroll currently only loads the next results if that page is moving, so this 'solution' would only work if it were fixed to work more like Twitter, polling until the viewport is filled. Even so, dozens of roundtrip requests to get to the first non-Blue reply seems like a much bigger waste of resources on both ends than supporting this filtering serverside.

uBO filter: `##span[title="Verified account"]:upward(div.reply)`

https://user-images.githubusercontent.com/29270864/236368555-abc34cd4-e32e-444f-a65d-ce34da0f5b4b.mp4

**Comment by zedeus** [comment]
> dozens of roundtrip requests to get to the first non-Blue reply 

And this is exactly whay it will not be implemented server-side. Having to do dozens of requests just to show a tweet isn't really acceptable.

**Comment by StyMaar** [comment]
> > dozens of roundtrip requests to get to the first non-Blue reply
> And this is exactly why it will not be implemented server-side. Having to do dozens of requests just to show a tweet isn't really acceptable.

Implementing this client-side doesn't solve the problem, and instead doubles the number of round trips so it's not like we have an alternative …

> To fix your issue just stop hiding every blue reply, it's silly and breaks this solution.

Blue replies are 95% spam / bot / trolls at this point, so it's not especially silly …

But of course you're free to implement whatever you want in your project.
