### ISSUE TITLE
instances are rate-limited

### ISSUE THREAD

**Issue by ghost** [zedeus/nitter#840]
this morning almost all the instances were rate-limited. we opened an instance and there was this message "Instance has been rate limited.  Use [another instance](https://github.com/zedeus/nitter/wiki/Instances) or try again later."
Arctic Foxes nitter and nitter.in.projectsegfau.lt were working without search i. e. they worked if I entered someone's handle manually into the URL

now instance front pages can be loaded but they're rate-limited if one searches for anything
![image](https://user-images.githubusercontent.com/126670115/233667402-6435eed0-1145-452b-bef8-5d42249ea227.png)

**Comment by zedeus** [comment]
This has been fixed by https://github.com/zedeus/nitter/commit/1ac389e7c75ced1762aa9c698ca2899cde668424, the instance hosters just need to update.

**Comment by sylentpunk** [comment]
Just git pulled and restarted my instance and I'm still getting rate limited myself.
https://nitter.sylentpunk.xyz

**Comment by zedeus** [comment]
You need to wait up to 30 minutes for the rate limit to be gone.

**Comment by pklion** [comment]
Seems still doesn't work...

**Comment by sylentpunk** [comment]
Yea, I'm still having the issue. If it means anything, twitter no longer allows people to use the search feature without signing in. Not sure if that's related.

**Comment by zedeus** [comment]
Related for instances that haven't been updated yet, I already made a replacement https://github.com/zedeus/nitter/issues/839

**Comment by zedeus** [comment]
@sylentpunk you're running a very old version 
![image](https://user-images.githubusercontent.com/9434921/233804529-052548aa-b28e-4851-b3fb-d3f0bc1061b3.png)

**Comment by sylentpunk** [comment]
I forgot to build it after the update.. -_- my bad
I don't run the docker version just cuz I already have so many other docker stuff running.
